general {
    col.active_border = rgb(FF5252)
    col.inactive_border = rgb(343944)
    border_size = 2
    gaps_in = 4
    gaps_out = 6
}
group {
    col.border_active = rgba(FF5252ee)
    col.border_inactive = rgb(343944)
    groupbar { col.active = rgba(E53935ff); col.inactive = rgba(11131Acc); text_color = rgb(F5F7FA); text_color_inactive = rgb(A9B0BA) }
}
decoration { rounding = 3; shadow { enabled = yes; render_power = 4; range = 16; color = rgba(00000066) } }
